"""Read/write access to rgmc-worker-pool's Firestore SO-import buffer, plus two sibling
collections for manual reconciliation links.

Collections (named per config.GCP_ENV, matching rgmc-worker-pool's src/services/so_buffer.py):
  so_buffer_{env}            — buffered/failed POUL SO-import orders. The doc itself
                                (header/lines/company/src_company/last_error/
                                attempt_count) is owned and written by rgmc-worker-pool
                                (so_buffer.save_failed_order/delete_buffered_order).
                                This module reads it, and (via apply_resolution_to_buffer/
                                clear_resolution_from_buffer) additively patches
                                header.resolvedShipTo/resolvedCustomer and per-line
                                resolvedItem fields directly onto the affected record —
                                every other field is left untouched.
  so_buffer_overrides_{env}  — the CURRENT manual link for a raw SKU code / customer
                                branch name / customer name — one doc per (type, key),
                                upserted. This is what the reconciliation UI matches
                                against to mark a group "resolved"; the buffer-doc patch
                                above is a denormalized copy of the same resolution,
                                written to the exact record(s) it applies to.
  so_buffer_reference_{env}  — an APPEND-ONLY history of every resolution ever saved
                                (never overwritten, one doc per save). Kept so a
                                previously-seen SKU/branch/customer can be looked up
                                for reference on a future upload even after its "current"
                                override has since been changed or superseded, and so a
                                future automated consumer (e.g. rgmc-worker-pool, once it
                                honors overrides) has a durable log to audit against.
  reprocess_runs_{env}       — one doc per manual reprocess-buffer trigger from the
                                /reconcile page, keyed by run_id (generated by
                                rgmc-gcp-api's POST /customerpoul/reprocess-buffer).
                                Owned and written by rgmc-worker-pool
                                (reprocess_status.start_run/finish_run) as it processes
                                the corresponding Pub/Sub message. This module only
                                reads it, for the /reconcile page's ongoing/done/error
                                status display.
  so_buffer_inactive_skus_{env} — raw SKU codes (or descriptions, for blank-SKU groups)
                                a human has marked inactive — e.g. a discontinued item
                                that will never get a real BC link. Deliberately
                                separate from so_buffer_overrides_{env}: this is an
                                exclusion flag with no BC record attached, not a
                                resolution. The /reconcile page uses it to move a SKU
                                group out of the Items (SKU) tab into its own Inactive
                                Items tab and drop it from the SKU resolved/total counts.
  so_buffer_history_{env}    — an APPEND-ONLY log of every PO a manual reprocess-buffer
                                run touched: {po_ref, header, lines, company, outcome
                                ("resolved"/"still_buffered"/"failed"), so_number, run_id,
                                triggered_by (the notify block of whoever clicked
                                Reprocess Buffer on /reconcile), triggered_at}. Owned and
                                written by rgmc-worker-pool (so_buffer_history.
                                record_reconciliation), one doc per PO per reprocess-
                                buffer attempt — this module only reads it, for the
                                /reconcile page's History tab. Distinct from
                                so_buffer_reference_{env} (that's the override-link
                                history; this is the buffer-reconciliation attempt
                                history, and survives after a PO's so_buffer_{env} doc
                                is deleted).

The resolved* fields written directly onto the buffer doc (header.resolvedShipTo/
resolvedCustomer, line.resolvedItem) ARE consumed by rgmc-worker-pool's reprocess logic —
so_import_worker.py's _create_order/_resolve_valid_lines check them first, ahead of their
own automatic ship-to/item matching from the raw text fields on each buffered order.
"""
import logging
import time
from typing import Any, Dict, List, Optional

from google.cloud import firestore
from google.cloud.firestore_v1.base_query import FieldFilter

from src import config

logger = logging.getLogger("so_buffer_service")

_db: Optional[firestore.Client] = None

VALID_OVERRIDE_TYPES = ("sku", "branch", "customer", "uom")


def _firestore() -> firestore.Client:
    global _db
    if _db is None:
        _db = firestore.Client(project=config.GCP_PROJECT_ID)
    return _db


def _env_slug() -> str:
    return (config.GCP_ENV or "staging").lower().replace(" ", "_")


def _buffer_collection() -> str:
    return f"so_buffer_{_env_slug()}"


def _overrides_collection() -> str:
    return f"so_buffer_overrides_{_env_slug()}"


def _reference_collection() -> str:
    return f"so_buffer_reference_{_env_slug()}"


def _reprocess_runs_collection() -> str:
    return f"reprocess_runs_{_env_slug()}"


def _inactive_skus_collection() -> str:
    return f"so_buffer_inactive_skus_{_env_slug()}"


def _history_collection() -> str:
    return f"so_buffer_history_{_env_slug()}"


def list_buffered_orders(company: Optional[str] = None) -> List[Dict[str, Any]]:
    """Return every buffered order as {"id": doc_id, **doc_data}.

    doc_data shape (written by rgmc-worker-pool's so_buffer.save_failed_order):
      header: dict (poRefNumber, customerName, customerBranchName,
              customerBranchLookUpCode, poDate, deliveryDate, ...)
      lines: list[dict] (customerSKUCode, customerSKUDesc, poQty, poQtyPcs, ...)
      company: str (BC company code, e.g. "SBIC")
      src_company: str
      last_error: str
      failed_at: timestamp
      attempt_count: int

    Read-only mirror — this collection is small (tens of documents), so no pagination.
    """
    db = _firestore()
    query = db.collection(_buffer_collection())
    if company:
        query = query.where(filter=FieldFilter("company", "==", company))
    return [{"id": doc.id, **(doc.to_dict() or {})} for doc in query.stream()]


def _buffer_doc_id(po_ref_number: Optional[str]) -> str:
    """Mirrors rgmc-worker-pool's so_buffer._doc_id exactly (same transform) — so a
    later worker-pool write/read for the same PO ref lands on the same document
    instead of creating a duplicate buffer entry for one PO."""
    return str(po_ref_number or "unknown").replace("/", "_").replace(".", "_")


def create_buffer_entry(
    header: Dict[str, Any],
    lines: List[Dict[str, Any]],
    company: str,
    src_company: str,
    created_by: str,
) -> Dict[str, Any]:
    """Manually place a new order into the SO-import buffer — e.g. from the
    manual-trigger page's BigQuery lookup, for a PO that was never picked up by the
    normal automated import path at all.

    Mirrors rgmc-worker-pool's so_buffer.save_failed_order doc shape and doc-ID scheme
    exactly (same collection, same slugified-poRefNumber doc ID) so the existing
    reprocess-buffer flow, /reconcile's Buffer tab, and everything else that reads
    so_buffer_{env} treats this identically to a worker-created entry — it just hasn't
    actually been attempted yet (attempt_count stays 0 until a real reprocess pass
    tries it). Upserts rather than erroring on an existing doc for the same PO ref,
    matching save_failed_order's own idempotent re-save behavior.
    """
    doc_id = _buffer_doc_id(header.get("poRefNumber"))
    doc_ref = _firestore().collection(_buffer_collection()).document(doc_id)
    payload = {
        "header": header,
        "lines": lines,
        "company": company,
        "src_company": src_company,
        "last_error": f"Manually added to the buffer by {created_by or 'a user'} via the BigQuery lookup — not yet attempted.",
        "failed_at": firestore.SERVER_TIMESTAMP,
        "attempt_count": 0,
    }
    doc_ref.set(payload)
    logger.info(f"so_buffer: manually created {doc_id!r} in {_buffer_collection()!r} (company={company!r}) by {created_by!r}")
    return {"id": doc_id, **payload}


def _line_key(line: Dict[str, Any]) -> str:
    """Same raw-SKU identity used to match a line to a sku override (apply_resolution_to_buffer/
    clear_resolution_from_buffer) — customerSKUCode, falling back to customerSKUDesc when blank."""
    sku = (line.get("customerSKUCode") or "").strip()
    return (sku or (line.get("customerSKUDesc") or "").strip() or "(no SKU code, no description)").upper()


def add_missing_lines_to_buffer(po_ref_number: str, candidate_lines: List[Dict[str, Any]]) -> Optional[Dict[str, Any]]:
    """For a PO that's already sitting in the buffer (e.g. the worker already failed to
    import it and saved its own snapshot via save_failed_order), add only the
    candidate lines not already represented there — e.g. a BigQuery lookup turned up
    extra detail lines the originally-buffered snapshot never had.

    Deliberately `.update({"lines": ...})`, never `.set()` the whole doc — header,
    company, attempt_count, last_error, failed_at, and any resolvedShipTo/
    resolvedCustomer/resolvedItem already patched onto this doc must survive untouched.
    Returns None if this PO isn't buffered at all (caller should create a new entry
    instead — see create_buffer_entry).
    """
    doc_id = _buffer_doc_id(po_ref_number)
    doc_ref = _firestore().collection(_buffer_collection()).document(doc_id)
    snap = doc_ref.get()
    if not snap.exists:
        return None

    existing_lines = (snap.to_dict() or {}).get("lines") or []
    seen_keys = {_line_key(line) for line in existing_lines}
    new_lines = []
    for line in candidate_lines:
        key = _line_key(line)
        if key in seen_keys:
            continue
        seen_keys.add(key)
        new_lines.append(line)

    if new_lines:
        doc_ref.update({"lines": existing_lines + new_lines})
    logger.info(
        f"so_buffer: merged {len(new_lines)}/{len(candidate_lines)} candidate line(s) into "
        f"already-buffered {doc_id!r} in {_buffer_collection()!r} ({len(existing_lines)} line(s) already present)"
    )
    return {"id": doc_id, "lines_added": len(new_lines), "total_lines": len(existing_lines) + len(new_lines)}


def _override_doc_id(override_type: str, key: str) -> str:
    safe_key = "".join(c if c.isalnum() else "_" for c in key.strip().upper())
    return f"{override_type}_{safe_key}"[:1500]  # Firestore document ID length limit is 1500 bytes


def list_overrides(override_type: Optional[str] = None) -> List[Dict[str, Any]]:
    """Return every saved manual link as {"id": doc_id, **doc_data}."""
    db = _firestore()
    query = db.collection(_overrides_collection())
    if override_type:
        query = query.where(filter=FieldFilter("type", "==", override_type))
    return [{"id": doc.id, **(doc.to_dict() or {})} for doc in query.stream()]


def save_override(
    override_type: str,
    key: str,
    resolved: Dict[str, Any],
    resolved_by: str,
    buffer_ids: Optional[List[str]] = None,
) -> Dict[str, Any]:
    """Upsert a manual link for one raw SKU code / branch name / customer name.

    override_type: one of VALID_OVERRIDE_TYPES ("sku", "branch", "customer").
    key: the exact raw text value shared by every buffered order this override applies
         to (e.g. the line's customerSKUCode, or the header's customerBranchName /
         customerName) — matched case-insensitively via the document ID.
    resolved: the chosen BC record's fields, e.g. {"itemNo": "...", "description": "..."}
              for sku; {"customerNo": "...", "shipToCode": "...", "name": "..."} for
              branch; {"customerNo": "...", "displayName": "..."} for customer.
    resolved_by: free-text identifying who made the choice (shown back in the UI).
    buffer_ids: which so_buffer_{env} docs this was also patched onto (see
                apply_resolution_to_buffer) — stored here so delete_override can clear
                the exact same docs precisely, without re-scanning/matching by text.
    """
    doc_id = _override_doc_id(override_type, key)
    doc_ref = _firestore().collection(_overrides_collection()).document(doc_id)
    payload = {
        "type": override_type,
        "key": key,
        "resolved": resolved,
        "resolved_by": resolved_by,
        "resolved_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "buffer_ids": buffer_ids or [],
    }
    doc_ref.set(payload)
    logger.info(f"so_buffer_overrides: saved {doc_id!r} -> {resolved!r} (by {resolved_by!r})")

    # Append-only reference log — every save gets its own new doc, never overwritten.
    try:
        _firestore().collection(_reference_collection()).add(payload)
    except Exception as exc:
        logger.warning(f"so_buffer_reference: failed to log {doc_id!r} (non-fatal): {exc}")

    return {"id": doc_id, **payload}


def _uom_key_parts(key: str) -> tuple:
    """A "uom" override's key is composite — "{itemNo}::{raw unit-of-measure text}" —
    unlike sku/branch/customer's flat raw-text keys, because the same raw UOM text
    (e.g. "Cases") can legitimately map to a different BC UOM code per item."""
    item_no, _, raw_uom = key.partition("::")
    return item_no.strip().upper(), raw_uom.strip().upper()


def _line_uom_item_no(line: Dict[str, Any]) -> str:
    """The item this line was actually being submitted as when BC rejected its Unit of
    Measure Code — tagged by rgmc-worker-pool as line.uomIssue.itemNo at the moment of
    that specific rejection (see so_import_worker.py's _describe_line_rejection call
    sites), falling back to line.resolvedItem.itemNo for a line not yet re-tagged."""
    uom_issue = line.get("uomIssue") or {}
    return (uom_issue.get("itemNo") or (line.get("resolvedItem") or {}).get("itemNo") or "").strip().upper()


def apply_resolution_to_buffer(
    override_type: str,
    key: str,
    resolved: Dict[str, Any],
    buffer_ids: List[str],
) -> int:
    """Write a resolved link directly onto the affected buffered order doc(s) in
    so_buffer_{env}, in addition to the (type, key) upsert in so_buffer_overrides_{env}.

    This means the resolution travels with the order record itself rather than only
    living in a side lookup table keyed by raw text — if/when rgmc-worker-pool's
    reprocess logic is updated to consult it, it's already sitting right there.

    branch   -> header.resolvedShipTo = resolved    ({customerNo, shipToCode, name})
    customer -> header.resolvedCustomer = resolved  ({customerNo, displayName})
    sku      -> every line whose customerSKUCode (or, if blank, customerSKUDesc) matches
                `key` case-insensitively gets line.resolvedItem = resolved
    uom      -> every line whose resolved item (see _line_uom_item_no) and raw
                unitOfMeasurement text match key's "{itemNo}::{rawUom}" parts gets
                line.resolvedUom = resolved ({uomCode, description})

    Only touches the `header` or `lines` field on each doc (via .update(), not .set())
    — company/last_error/attempt_count/etc. are left untouched. Silently skips any
    buffer_id that no longer exists (e.g. already reprocessed and cleared). Returns the
    number of docs actually patched.
    """
    db = _firestore()
    collection = _buffer_collection()
    key_upper = key.strip().upper()
    item_no_upper, raw_uom_upper = _uom_key_parts(key) if override_type == "uom" else (None, None)
    patched = 0

    for buffer_id in buffer_ids:
        doc_ref = db.collection(collection).document(buffer_id)
        snap = doc_ref.get()
        if not snap.exists:
            continue
        data = snap.to_dict() or {}

        if override_type in ("branch", "customer"):
            header = data.get("header") or {}
            header["resolvedShipTo" if override_type == "branch" else "resolvedCustomer"] = resolved
            doc_ref.update({"header": header})
            patched += 1
        elif override_type == "sku":
            lines = data.get("lines") or []
            changed = False
            for line in lines:
                sku = (line.get("customerSKUCode") or "").strip()
                match_key = sku or (line.get("customerSKUDesc") or "").strip() or "(no SKU code, no description)"
                if match_key.upper() == key_upper:
                    line["resolvedItem"] = resolved
                    changed = True
            if changed:
                doc_ref.update({"lines": lines})
                patched += 1
        elif override_type == "uom":
            lines = data.get("lines") or []
            changed = False
            for line in lines:
                raw_uom = (line.get("unitOfMeasurement") or "").strip().upper()
                if _line_uom_item_no(line) == item_no_upper and raw_uom == raw_uom_upper:
                    line["resolvedUom"] = resolved
                    changed = True
            if changed:
                doc_ref.update({"lines": lines})
                patched += 1

    logger.info(
        f"so_buffer: applied {override_type}/{key!r} resolution to {patched}/{len(buffer_ids)} buffer doc(s)"
    )
    return patched


def _clear_field_by_ids(override_type: str, key: str, buffer_ids: List[str]) -> int:
    """Remove the resolved* field from exactly these buffer docs. Mirrors
    apply_resolution_to_buffer's targeting precisely, so undo removes exactly what
    the matching save applied — no re-derivation/matching involved.
    """
    db = _firestore()
    key_upper = key.strip().upper()
    item_no_upper, raw_uom_upper = _uom_key_parts(key) if override_type == "uom" else (None, None)
    field_name = {"branch": "resolvedShipTo", "customer": "resolvedCustomer"}.get(override_type)
    cleared = 0

    for buffer_id in buffer_ids:
        doc_ref = db.collection(_buffer_collection()).document(buffer_id)
        snap = doc_ref.get()
        if not snap.exists:
            continue
        data = snap.to_dict() or {}
        if override_type in ("branch", "customer"):
            header = data.get("header") or {}
            if field_name in header:
                del header[field_name]
                doc_ref.update({"header": header})
                cleared += 1
        elif override_type == "sku":
            lines = data.get("lines") or []
            changed = False
            for line in lines:
                sku = (line.get("customerSKUCode") or "").strip()
                match_key = sku or (line.get("customerSKUDesc") or "").strip() or "(no SKU code, no description)"
                if match_key.upper() == key_upper and "resolvedItem" in line:
                    del line["resolvedItem"]
                    changed = True
            if changed:
                doc_ref.update({"lines": lines})
                cleared += 1
        elif override_type == "uom":
            lines = data.get("lines") or []
            changed = False
            for line in lines:
                raw_uom = (line.get("unitOfMeasurement") or "").strip().upper()
                if _line_uom_item_no(line) == item_no_upper and raw_uom == raw_uom_upper and "resolvedUom" in line:
                    del line["resolvedUom"]
                    changed = True
            if changed:
                doc_ref.update({"lines": lines})
                cleared += 1

    return cleared


def clear_resolution_from_buffer(override_type: str, key: str) -> int:
    """Remove a resolved link from every buffered order doc that currently has it.

    Fallback for overrides saved before buffer_ids was tracked on the override doc:
    scans so_buffer_{env} (small — tens of docs) for headers/lines matching `key` the
    same way apply_resolution_to_buffer found them, and deletes the corresponding
    resolved* field. Prefer _clear_field_by_ids (exact, no scan) when buffer_ids is
    known — see delete_override.
    """
    db = _firestore()
    key_upper = key.strip().upper()
    item_no_upper, raw_uom_upper = _uom_key_parts(key) if override_type == "uom" else (None, None)
    field_name = {"branch": "resolvedShipTo", "customer": "resolvedCustomer"}.get(override_type)
    cleared = 0

    for doc in db.collection(_buffer_collection()).stream():
        data = doc.to_dict() or {}
        if override_type in ("branch", "customer"):
            header = data.get("header") or {}
            name_field = "customerBranchName" if override_type == "branch" else "customerName"
            if (header.get(name_field) or "").strip().upper() == key_upper and field_name in header:
                del header[field_name]
                doc.reference.update({"header": header})
                cleared += 1
        elif override_type == "sku":
            lines = data.get("lines") or []
            changed = False
            for line in lines:
                sku = (line.get("customerSKUCode") or "").strip()
                match_key = sku or (line.get("customerSKUDesc") or "").strip() or "(no SKU code, no description)"
                if match_key.upper() == key_upper and "resolvedItem" in line:
                    del line["resolvedItem"]
                    changed = True
            if changed:
                doc.reference.update({"lines": lines})
                cleared += 1
        elif override_type == "uom":
            lines = data.get("lines") or []
            changed = False
            for line in lines:
                raw_uom = (line.get("unitOfMeasurement") or "").strip().upper()
                if _line_uom_item_no(line) == item_no_upper and raw_uom == raw_uom_upper and "resolvedUom" in line:
                    del line["resolvedUom"]
                    changed = True
            if changed:
                doc.reference.update({"lines": lines})
                cleared += 1

    return cleared


def delete_override(doc_id: str) -> int:
    """Delete a saved override and clear the matching resolved* field from the buffer
    doc(s) it was applied to. Returns how many buffer docs were cleared."""
    doc_ref = _firestore().collection(_overrides_collection()).document(doc_id)
    snap = doc_ref.get()
    cleared = 0
    if snap.exists:
        data = snap.to_dict() or {}
        override_type, key = data.get("type"), data.get("key")
        stored_buffer_ids = data.get("buffer_ids") or []
        if override_type and key and stored_buffer_ids:
            cleared = _clear_field_by_ids(override_type, key, stored_buffer_ids)
        elif override_type and key:
            # Legacy override saved before buffer_ids was tracked — fall back to a scan.
            cleared = clear_resolution_from_buffer(override_type, key)
    doc_ref.delete()
    logger.info(f"so_buffer_overrides: deleted {doc_id!r}, cleared from {cleared} buffer doc(s)")
    return cleared


def list_reference(override_type: Optional[str] = None, key: Optional[str] = None) -> List[Dict[str, Any]]:
    """Return the resolution history, most recent first.

    Unlike list_overrides (current state, one row per key), this can return multiple
    rows for the same (type, key) if it was resolved more than once over time.
    """
    db = _firestore()
    query = db.collection(_reference_collection())
    if override_type:
        query = query.where(filter=FieldFilter("type", "==", override_type))
    if key:
        query = query.where(filter=FieldFilter("key", "==", key))
    docs = [{"id": doc.id, **(doc.to_dict() or {})} for doc in query.stream()]
    docs.sort(key=lambda d: d.get("resolved_at") or "", reverse=True)
    return docs


def get_reprocess_run(run_id: str) -> Dict[str, Any]:
    """Return one manual reprocess-buffer run's status: {status, companies, notify,
    summary, error, started_at, updated_at, finished_at}.

    status is "queued" (synthesized — no doc yet, meaning rgmc-worker-pool hasn't
    picked up the Pub/Sub message yet), "processing", "done", or "error". Firestore
    Timestamp fields are converted to ISO 8601 strings so the response is plain JSON.
    """
    snap = _firestore().collection(_reprocess_runs_collection()).document(run_id).get()
    if not snap.exists:
        return {"run_id": run_id, "status": "queued"}
    data = snap.to_dict() or {}
    for field in ("started_at", "updated_at", "finished_at"):
        value = data.get(field)
        if value is not None and hasattr(value, "isoformat"):
            data[field] = value.isoformat()
    return {"run_id": run_id, **data}


def list_inactive_skus() -> List[Dict[str, Any]]:
    """Return every SKU code/description marked inactive, as {"id": doc_id, **doc_data}."""
    db = _firestore()
    return [{"id": doc.id, **(doc.to_dict() or {})} for doc in db.collection(_inactive_skus_collection()).stream()]


def mark_sku_inactive(key: str, marked_by: str) -> Dict[str, Any]:
    """Upsert one raw SKU code (or description, for a blank-SKU group) as inactive.

    Reuses save_override's doc-id scheme (type "sku") so the two collections stay
    trivially joinable by key, though they're kept separate on purpose: this is an
    exclusion flag with no BC record attached, not a resolved link.
    """
    doc_id = _override_doc_id("sku", key)
    doc_ref = _firestore().collection(_inactive_skus_collection()).document(doc_id)
    payload = {
        "key": key,
        "marked_by": marked_by,
        "marked_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }
    doc_ref.set(payload)
    logger.info(f"so_buffer_inactive_skus: marked {doc_id!r} inactive (by {marked_by!r})")
    return {"id": doc_id, **payload}


def unmark_sku_inactive(doc_id: str) -> None:
    """Reactivate a SKU previously marked inactive (undo mark_sku_inactive)."""
    _firestore().collection(_inactive_skus_collection()).document(doc_id).delete()
    logger.info(f"so_buffer_inactive_skus: reactivated {doc_id!r}")


def list_buffer_history(
    company: Optional[str] = None,
    po_ref: Optional[str] = None,
    outcome: Optional[str] = None,
    run_id: Optional[str] = None,
    limit: int = 200,
) -> List[Dict[str, Any]]:
    """Return buffer-reconciliation history records, most recent first.

    Each record is one PO as it stood during one reprocess-buffer attempt — written by
    rgmc-worker-pool's so_buffer_history.record_reconciliation, never overwritten, so a
    PO's reconciliation trail survives even after its so_buffer_{env} doc is deleted.
    """
    db = _firestore()
    query = db.collection(_history_collection())
    if company:
        query = query.where(filter=FieldFilter("company", "==", company))
    if po_ref:
        query = query.where(filter=FieldFilter("po_ref", "==", po_ref))
    if outcome:
        query = query.where(filter=FieldFilter("outcome", "==", outcome))
    if run_id:
        query = query.where(filter=FieldFilter("run_id", "==", run_id))
    docs = [{"id": doc.id, **(doc.to_dict() or {})} for doc in query.stream()]
    for doc in docs:
        value = doc.get("triggered_at")
        if value is not None and hasattr(value, "isoformat"):
            doc["triggered_at"] = value.isoformat()
    docs.sort(key=lambda d: d.get("triggered_at") or "", reverse=True)
    return docs[:limit]


def record_history_entry(
    header: Dict[str, Any],
    lines: List[Dict[str, Any]],
    company: str,
    outcome: str,
    triggered_by: Optional[Dict[str, Any]] = None,
    so_number: Optional[str] = None,
    detail: Optional[str] = None,
) -> Dict[str, Any]:
    """Append one so_buffer_history_{env} record from rgmc-bc-api's own side — mirrors
    rgmc-worker-pool's so_buffer_history.record_reconciliation payload shape exactly
    (same collection, same fields), so this shows up in /reconcile's History tab
    identically to a worker-driven reprocess attempt.

    Used by the BigQuery-lookup "insert into MSSQL + buffer" action when it's BLOCKED
    by an already-existing BC Sales Order for the same PO ref — the blocked attempt
    still gets a record here (outcome "resolved" if the existing order's lines already
    look complete, "still_buffered" if some appear to be missing) instead of silently
    vanishing just because nothing was inserted.
    """
    payload = {
        "po_ref": header.get("poRefNumber", "unknown"),
        "header": header,
        "lines": lines,
        "company": company,
        "outcome": outcome,
        "so_number": so_number,
        "run_id": None,
        "triggered_by": triggered_by,
        "triggered_at": firestore.SERVER_TIMESTAMP,
    }
    if detail:
        payload["detail"] = detail
    _, doc_ref = _firestore().collection(_history_collection()).add(payload)
    logger.info(f"so_buffer_history: recorded {payload['po_ref']!r} outcome={outcome!r} (company={company!r}) via rgmc-bc-api")
    return {"id": doc_ref.id, **payload}
